import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AppConfig:
    bubble_model_path: Path = Path("models/bubble_seg.pt")
    hf_bubble_model_repo: str = "kitsumed/yolov8m_seg-speech-bubble"
    hf_bubble_model_filename: str = "model.pt"
    auto_download_bubble_model: bool = True
    output_dir: Path = Path("output")
    translation_provider: str = os.getenv("TRANSLATION_PROVIDER", "m2m100")
    translation_model: str = os.getenv("TRANSLATION_MODEL", "facebook/m2m100_418M")
    translation_cache_enabled: bool = os.getenv("TRANSLATION_CACHE_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
    translation_timeout_seconds: int = int(os.getenv("TRANSLATION_TIMEOUT_SECONDS", "180"))
    translation_beam_size: int = 4
    translation_mode: str = "en_to_pt"
    source_lang: str = os.getenv("DEFAULT_SOURCE_LANG", "auto")
    target_lang: str = os.getenv("DEFAULT_TARGET_LANG", "pt")
    ocr_lang: str = "en"
    translation_style: str = "natural"
    performance_mode: str = "balanced"
    yolo_confidence: float = 0.20
    yolo_iou: float = 0.50
    yolo_imgsz: int = 960
    bubble_erode_px: int = 8
    text_mask_dilate_px: int = 15
    render_margin_px: int = 14
    translation_font_scale: float = 1.0
    min_font_size: int = 9
    max_font_size: int = 32
    inpaint_radius: int = 3
    use_gpu: bool = False
    min_bubble_area: int = 300
    min_bubble_width: int = 20
    min_bubble_height: int = 20
    min_ocr_area: int = 900
    min_ocr_width: int = 24
    min_ocr_height: int = 18
    min_ocr_dark_ratio: float = 0.001
    ocr_cache_max_items: int = 256
    bubble_mask_close_px: int = 5
    bubble_mask_open_px: int = 3
    use_dark_text_fallback: bool = True
    dark_text_threshold: int = 200
    max_cleanup_mask_ratio: float = 0.65
    min_text_component_area: int = 4
    max_text_component_area_ratio: float = 0.12
    cleanup_morph_close_px: int = 5
    cleanup_extra_dilate_px: int = 5
    cleaner_mode: str = "white_fill"
    force_clean_on_failed_mask: bool = True
    inner_white_fill_on_failed_cleanup: bool = True
    line_spacing_ratio: float = 1.12
    font_shrink_step: int = 1
    max_render_font_attempts: int = 28
    text_padding_px: int = 8
    draw_text_outline: bool = False
    text_color: tuple[int, int, int] = (0, 0, 0)
    outline_color: tuple[int, int, int] = (255, 255, 255)
    auto_font_resize: bool = True
    center_text: bool = True
    bold_text: bool = False
    cleanup_feather_px: int = 2
    residual_dark_threshold: int = 100
    residual_min_component_area: int = 6
    residual_max_component_ratio: float = 0.04
    residual_max_ratio: float = 0.025
    debug_enabled: bool = False
    debug_dir: Path | None = None
